### ISSUE TITLE
Doesn't work with Robolectric unit tests

### ISSUE THREAD

**Issue by MuntashirAkon** [YarikSOffice/lingver#43]
You'd get the following error if you use Robolectric for unit testing. The current workaround is to catch `IllegalStateException`.

```
java.lang.IllegalStateException: Already initialized
at com.yariksoffice.lingver.Lingver$Companion.init(Lingver.kt:192)
at com.yariksoffice.lingver.Lingver$Companion.init(Lingver.kt:182)
at com.yariksoffice.lingver.Lingver.init(Lingver.kt)
```

This happens because Robolectric calls `Application#onCreate()` on each test.

**Comment by Grch** [comment]
Have you found any workaround? I can't launch unit tests

**Comment by MuntashirAkon** [comment]
> Have you found any workaround? I can't launch unit tests

Create a [custom Application test class](http://robolectric.org/configuring/#configure-application-class) for Robolectric tests.
